# Generated by Django 2.1.7 on 2019-03-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name ')),
                ('stu_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('room_number', models.TextField(blank=True, null=True)),
                ('hall', models.TextField(blank=True, null=True)),
                ('signed_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Signed in at')),
            ],
        ),
    ]
