# Generated by Django 2.1.7 on 2019-03-15 14:37

from django.db import migrations

def demo_data(apps,schema_editor):
    Student = apps.get_model('students','Student')
    Student(first_name="samuel",last_name="Adetunji",stu_email="samuel.adeunji@stu.cu.edu.ng",phone="00000",room_number="A202",hall="paul").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(demo_data),

    ]
